# Generated by Django 5.1.1 on 2024-09-11 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha_treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField()),
                ('segunda_feira', models.CharField(max_length=100)),
                ('terca_feira', models.CharField(max_length=100)),
                ('quarta_feira', models.CharField(max_length=100)),
                ('quinta_feira', models.CharField(max_length=100)),
                ('sexta_feira', models.CharField(max_length=100)),
                ('sabado', models.CharField(max_length=100)),
                ('domingo', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamicos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Calculo_imc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('imc', models.CharField(max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinamicos.usuario')),
            ],
        ),
    ]
