# Generated by Django 5.1.1 on 2024-10-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha_treino',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='ficha_treino',
            name='quarta_feira',
        ),
        migrations.RemoveField(
            model_name='ficha_treino',
            name='quinta_feira',
        ),
        migrations.RemoveField(
            model_name='ficha_treino',
            name='segunda_feira',
        ),
        migrations.RemoveField(
            model_name='ficha_treino',
            name='sexta_feira',
        ),
        migrations.RemoveField(
            model_name='ficha_treino',
            name='terca_feira',
        ),
        migrations.RemoveField(
            model_name='ficha_treino',
            name='usuario',
        ),
        migrations.AddField(
            model_name='ficha_treino',
            name='nome',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_treino',
            name='quarta',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_treino',
            name='quinta',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_treino',
            name='segunda',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_treino',
            name='sexta',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ficha_treino',
            name='terca',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
