# Generated by Django 5.1.1 on 2024-10-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicos', '0002_remove_ficha_treino_data_criacao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculo_imc',
            new_name='CalculoImc',
        ),
        migrations.RenameModel(
            old_name='Ficha_treino',
            new_name='FichaTreino',
        ),
    ]
