# Generated by Django 5.1.1 on 2024-11-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinamicos', '0003_rename_calculo_imc_calculoimc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CalculoImc',
        ),
    ]
